package com.fym.lta.UI;

import com.fym.lta.BAO.BaoFactory;
import com.fym.lta.BAO.RoleScreenBao;
import com.fym.lta.DTO.UserDto;

import java.awt.Color;

import java.util.ArrayList;

/**
 *
 * @author Mai-AbdEltwab
 */
public class DataBasePanel extends javax.swing.JPanel
{
  @SuppressWarnings("compatibility:4012648287550807639")
  private static final long serialVersionUID = 1L;

  /**Definitions*/
  //define user dto as "user"
  private static UserDto user;
  
  /** Creates new form DataBasePanel */
  public DataBasePanel(UserDto user)
  {

    //assign logged in user to user_account object
    DataBasePanel.user = user;

    //set panel components
    initComponents();

    //set all panels buttons false
    setPanelsFalse();

    //set panels buttons ture which only user has access on it
    checkSecuirty();

  }


  /**This method for role screen
   * set panels buttons ture which only user role has access on it
   */
  private void checkSecuirty()
  {

    //create role screen bao 
    RoleScreenBao userPanel_bao =
      new BaoFactory().createRoleScreenBao(user);
 
    //get all existing screens for this user 
    ArrayList<String> panels =
      new ArrayList<String>(userPanel_bao.checkPanel(user));

    /* get check for each screen
     * if its name match any button text enable this button*/
    for(int i = 0; i<panels.size(); i++) 
      {
        //for location type screen
        if(LocationTypeButton.getText().equalsIgnoreCase(panels.get(i)))
          LocationTypeButton.setEnabled(true);
        //for location screen
        if(LocationButton.getText().equalsIgnoreCase(panels.get(i)))
          LocationButton.setEnabled(true);
        //for floor screen
        if(FloorButton.getText().equalsIgnoreCase(panels.get(i)))
          FloorButton.setEnabled(true);

        //for building screen
        if(buildingButton.getText().equalsIgnoreCase(panels.get(i)))
          buildingButton.setEnabled(true);
        //for department screen
        if(DepartmentButton.getText().equalsIgnoreCase(panels.get(i)))
          DepartmentButton.setEnabled(true);
        //for course screen
        if(CourseButton.getText().equalsIgnoreCase(panels.get(i)))
          CourseButton.setEnabled(true);
        //for staff screen
        if(StaffButton.getText().equalsIgnoreCase(panels.get(i)))
          StaffButton.setEnabled(true);
        
        //for employee screen
        if(EmployeeButton.getText().equalsIgnoreCase(panels.get(i)))
          EmployeeButton.setEnabled(true);
        //for user screen
        if(UserButton.getText().equalsIgnoreCase(panels.get(i)))
          UserButton.setEnabled(true);
        //for role screen
        if(RoleButton.getText().equalsIgnoreCase(panels.get(i)))
          RoleButton.setEnabled(true);
        //for role screen screen
        if(RoleScreenButton.getText().equalsIgnoreCase(panels.get(i)))
          RoleScreenButton.setEnabled(true);
        
        //for equipment screen
        if(EquipmentButton.getText().equalsIgnoreCase(panels.get(i)))
          EquipmentButton.setEnabled(true);
        //for equipment type screen
        if(EquipmentTypeButton.getText().equalsIgnoreCase(panels.get(i)))
          EquipmentTypeButton.setEnabled(true);
        //for equipment specification screen
        if(EquipSpecsButton.getText().equalsIgnoreCase(panels.get(i)))
          EquipSpecsButton.setEnabled(true);

      }

  }


  /**set method used to set all panels bottuns disabled
   * */
  private void setPanelsFalse()
  {

    LocationTypeButton.setEnabled(false);
    LocationButton.setEnabled(false);
    FloorButton.setEnabled(false);
    buildingButton.setEnabled(false);

    DepartmentButton.setEnabled(false);
    CourseButton.setEnabled(false);
    StaffButton.setEnabled(false);

    EmployeeButton.setEnabled(false);
    UserButton.setEnabled(false);
    RoleButton.setEnabled(false);
    RoleScreenButton.setEnabled(false);

    EquipmentButton.setEnabled(false);
    EquipmentTypeButton.setEnabled(false);
    EquipSpecsButton.setEnabled(false);

  }

  /** This method is called from within the constructor to
   * initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is
   * always regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  private void initComponents()//GEN-BEGIN:initComponents
  {

    departmentManagerPanel = new javax.swing.JPanel();
    departmentSectionImage = new javax.swing.JLabel();
    arrow7 = new javax.swing.JLabel();
    arrow8 = new javax.swing.JLabel();
    arrow9 = new javax.swing.JLabel();
    CourseButton = new javax.swing.JButton();
    StaffButton = new javax.swing.JButton();
    DepartmentButton = new javax.swing.JButton();
    equipmentManagerPanel = new javax.swing.JPanel();
    equipmentSectionImage = new javax.swing.JLabel();
    arrow11 = new javax.swing.JLabel();
    arrow12 = new javax.swing.JLabel();
    arrow13 = new javax.swing.JLabel();
    EquipmentTypeButton = new javax.swing.JButton();
    EquipSpecsButton = new javax.swing.JButton();
    EquipmentButton = new javax.swing.JButton();
    locationManagerPanel = new javax.swing.JPanel();
    LactionSectionImage = new javax.swing.JLabel();
    arrow1 = new javax.swing.JLabel();
    arrow3 = new javax.swing.JLabel();
    arrow4 = new javax.swing.JLabel();
    arrow5 = new javax.swing.JLabel();
    LocationButton = new javax.swing.JButton();
    FloorButton = new javax.swing.JButton();
    buildingButton = new javax.swing.JButton();
    LocationTypeButton = new javax.swing.JButton();
    usersManagerPanel = new javax.swing.JPanel();
    userSectionImage = new javax.swing.JLabel();
    arrow16 = new javax.swing.JLabel();
    arrow17 = new javax.swing.JLabel();
    arrow18 = new javax.swing.JLabel();
    arrow19 = new javax.swing.JLabel();
    UserButton = new javax.swing.JButton();
    RoleButton = new javax.swing.JButton();
    RoleScreenButton = new javax.swing.JButton();
    EmployeeButton = new javax.swing.JButton();

    setBackground(new java.awt.Color(228, 228, 228));
    setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

    departmentManagerPanel.setBackground(new java.awt.Color(255, 255, 255));
    departmentManagerPanel.setToolTipText("");
    departmentManagerPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

    departmentSectionImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/fym/lta/Images/icons8_org_unit_128px.png"))); // NOI18N
    departmentManagerPanel.add(departmentSectionImage, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 30, -1, -1));

    arrow7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/fym/lta/Images/icons8_circled_chevron_right_filled_30px.png"))); // NOI18N
    departmentManagerPanel.add(arrow7, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 180, -1, 40));

    arrow8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/fym/lta/Images/icons8_circled_chevron_right_filled_30px.png"))); // NOI18N
    departmentManagerPanel.add(arrow8, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 230, -1, 41));

    arrow9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/fym/lta/Images/icons8_circled_chevron_right_filled_30px.png"))); // NOI18N
    departmentManagerPanel.add(arrow9, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 280, -1, 42));

    CourseButton.setBackground(new java.awt.Color(255, 255, 255));
    CourseButton.setFont(new java.awt.Font("VIP Rawy Regular", 0, 24)); // NOI18N
    CourseButton.setText("Course");
    CourseButton.setToolTipText("");
    CourseButton.setBorderPainted(false);
    CourseButton.setContentAreaFilled(false);
    CourseButton.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
    CourseButton.addMouseMotionListener(new java.awt.event.MouseMotionAdapter()
    {
      public void mouseMoved(java.awt.event.MouseEvent evt)
      {
        CourseButtonMouseMoved(evt);
      }
    });
    CourseButton.addMouseListener(new java.awt.event.MouseAdapter()
    {
      public void mousePressed(java.awt.event.MouseEvent evt)
      {
        CourseButtonMousePressed(evt);
      }
      public void mouseExited(java.awt.event.MouseEvent evt)
      {
        CourseButtonMouseExited(evt);
      }
    });
    CourseButton.addActionListener(new java.awt.event.ActionListener()
    {
      public void actionPerformed(java.awt.event.ActionEvent evt)
      {
        CourseButtonActionPerformed(evt);
      }
    });
    departmentManagerPanel.add(CourseButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 230, 140, 40));

    StaffButton.setBackground(new java.awt.Color(255, 255, 255));
    StaffButton.setFont(new java.awt.Font("VIP Rawy Regular", 0, 24)); // NOI18N
    StaffButton.setText("Staff");
    StaffButton.setToolTipText("");
    StaffButton.setBorderPainted(false);
    StaffButton.setContentAreaFilled(false);
    StaffButton.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
    StaffButton.addMouseMotionListener(new java.awt.event.MouseMotionAdapter()
    {
      public void mouseMoved(java.awt.event.MouseEvent evt)
      {
        StaffButtonMouseMoved(evt);
      }
    });
    StaffButton.addMouseListener(new java.awt.event.MouseAdapter()
    {
      public void mousePressed(java.awt.event.MouseEvent evt)
      {
        StaffButtonMousePressed(evt);
      }
      public void mouseExited(java.awt.event.MouseEvent evt)
      {
        StaffButtonMouseExited(evt);
      }
    });
    StaffButton.addActionListener(new java.awt.event.ActionListener()
    {
      public void actionPerformed(java.awt.event.ActionEvent evt)
      {
        StaffButtonActionPerformed(evt);
      }
    });
    departmentManagerPanel.add(StaffButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 280, 140, 40));

    DepartmentButton.setBackground(new java.awt.Color(255, 255, 255));
    DepartmentButton.setFont(new java.awt.Font("VIP Rawy Regular", 0, 24)); // NOI18N
    DepartmentButton.setText("Department");
    DepartmentButton.setToolTipText("");
    DepartmentButton.setBorderPainted(false);
    DepartmentButton.setContentAreaFilled(false);
    DepartmentButton.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
    DepartmentButton.addMouseMotionListener(new java.awt.event.MouseMotionAdapter()
    {
      public void mouseMoved(java.awt.event.MouseEvent evt)
      {
        DepartmentButtonMouseMoved(evt);
      }
    });
    DepartmentButton.addMouseListener(new java.awt.event.MouseAdapter()
    {
      public void mousePressed(java.awt.event.MouseEvent evt)
      {
        DepartmentButtonMousePressed(evt);
      }
      public void mouseExited(java.awt.event.MouseEvent evt)
      {
        DepartmentButtonMouseExited(evt);
      }
    });
    DepartmentButton.addActionListener(new java.awt.event.ActionListener()
    {
      public void actionPerformed(java.awt.event.ActionEvent evt)
      {
        DepartmentButtonActionPerformed(evt);
      }
    });
    departmentManagerPanel.add(DepartmentButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 180, 190, 40));

    add(departmentManagerPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 70, 390, 390));

    equipmentManagerPanel.setBackground(new java.awt.Color(255, 255, 255));
    equipmentManagerPanel.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
    equipmentManagerPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

    equipmentSectionImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/fym/lta/Images/icons8_maintenance_128px.png"))); // NOI18N
    equipmentManagerPanel.add(equipmentSectionImage, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 40, -1, -1));

    arrow11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/fym/lta/Images/icons8_circled_chevron_right_filled_30px.png"))); // NOI18N
    equipmentManagerPanel.add(arrow11, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 190, -1, 40));

    arrow12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/fym/lta/Images/icons8_circled_chevron_right_filled_30px.png"))); // NOI18N
    equipmentManagerPanel.add(arrow12, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 240, -1, 41));

    arrow13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/fym/lta/Images/icons8_circled_chevron_right_filled_30px.png"))); // NOI18N
    equipmentManagerPanel.add(arrow13, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 290, -1, 42));

    EquipmentTypeButton.setBackground(new java.awt.Color(255, 255, 255));
    EquipmentTypeButton.setFont(new java.awt.Font("VIP Rawy Regular", 0, 24)); // NOI18N
    EquipmentTypeButton.setText("Equipment type");
    EquipmentTypeButton.setToolTipText("");
    EquipmentTypeButton.setBorderPainted(false);
    EquipmentTypeButton.setContentAreaFilled(false);
    EquipmentTypeButton.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
    EquipmentTypeButton.addMouseMotionListener(new java.awt.event.MouseMotionAdapter()
    {
      public void mouseMoved(java.awt.event.MouseEvent evt)
      {
        EquipmentTypeButtonMouseMoved(evt);
      }
    });
    EquipmentTypeButton.addMouseListener(new java.awt.event.MouseAdapter()
    {
      public void mousePressed(java.awt.event.MouseEvent evt)
      {
        EquipmentTypeButtonMousePressed(evt);
      }
      public void mouseExited(java.awt.event.MouseEvent evt)
      {
        EquipmentTypeButtonMouseExited(evt);
      }
    });
    EquipmentTypeButton.addActionListener(new java.awt.event.ActionListener()
    {
      public void actionPerformed(java.awt.event.ActionEvent evt)
      {
        EquipmentTypeButtonActionPerformed(evt);
      }
    });
    equipmentManagerPanel.add(EquipmentTypeButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 240, 200, 40));

    EquipSpecsButton.setBackground(new java.awt.Color(255, 255, 255));
    EquipSpecsButton.setFont(new java.awt.Font("VIP Rawy Regular", 0, 24)); // NOI18N
    EquipSpecsButton.setText("Equipment Specification");
    EquipSpecsButton.setToolTipText("");
    EquipSpecsButton.setBorderPainted(false);
    EquipSpecsButton.setContentAreaFilled(false);
    EquipSpecsButton.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
    EquipSpecsButton.addMouseMotionListener(new java.awt.event.MouseMotionAdapter()
    {
      public void mouseMoved(java.awt.event.MouseEvent evt)
      {
        EquipSpecsButtonMouseMoved(evt);
      }
    });
    EquipSpecsButton.addMouseListener(new java.awt.event.MouseAdapter()
    {
      public void mousePressed(java.awt.event.MouseEvent evt)
      {
        EquipSpecsButtonMousePressed(evt);
      }
      public void mouseExited(java.awt.event.MouseEvent evt)
      {
        EquipSpecsButtonMouseExited(evt);
      }
    });
    EquipSpecsButton.addActionListener(new java.awt.event.ActionListener()
    {
      public void actionPerformed(java.awt.event.ActionEvent evt)
      {
        EquipSpecsButtonActionPerformed(evt);
      }
    });
    equipmentManagerPanel.add(EquipSpecsButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 290, 310, 40));

    EquipmentButton.setBackground(new java.awt.Color(255, 255, 255));
    EquipmentButton.setFont(new java.awt.Font("VIP Rawy Regular", 0, 24)); // NOI18N
    EquipmentButton.setText("Equipment");
    EquipmentButton.setToolTipText("");
    EquipmentButton.setBorderPainted(false);
    EquipmentButton.setContentAreaFilled(false);
    EquipmentButton.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
    EquipmentButton.addMouseMotionListener(new java.awt.event.MouseMotionAdapter()
    {
      public void mouseMoved(java.awt.event.MouseEvent evt)
      {
        EquipmentButtonMouseMoved(evt);
      }
    });
    EquipmentButton.addMouseListener(new java.awt.event.MouseAdapter()
    {
      public void mousePressed(java.awt.event.MouseEvent evt)
      {
        EquipmentButtonMousePressed(evt);
      }
      public void mouseExited(java.awt.event.MouseEvent evt)
      {
        EquipmentButtonMouseExited(evt);
      }
    });
    EquipmentButton.addActionListener(new java.awt.event.ActionListener()
    {
      public void actionPerformed(java.awt.event.ActionEvent evt)
      {
        EquipmentButtonActionPerformed(evt);
      }
    });
    equipmentManagerPanel.add(EquipmentButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 190, 210, 40));

    add(equipmentManagerPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 510, 400, 400));

    locationManagerPanel.setBackground(new java.awt.Color(255, 255, 255));
    locationManagerPanel.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
    locationManagerPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

    LactionSectionImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/fym/lta/Images/icons8_geo_fence_128px.png"))); // NOI18N
    locationManagerPanel.add(LactionSectionImage, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 30, -1, -1));

    arrow1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/fym/lta/Images/icons8_circled_chevron_right_filled_30px.png"))); // NOI18N
    locationManagerPanel.add(arrow1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 180, -1, 40));

    arrow3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/fym/lta/Images/icons8_circled_chevron_right_filled_30px.png"))); // NOI18N
    locationManagerPanel.add(arrow3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 230, -1, 41));

    arrow4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/fym/lta/Images/icons8_circled_chevron_right_filled_30px.png"))); // NOI18N
    locationManagerPanel.add(arrow4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 280, -1, 42));

    arrow5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/fym/lta/Images/icons8_circled_chevron_right_filled_30px.png"))); // NOI18N
    locationManagerPanel.add(arrow5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 330, -1, 40));

    LocationButton.setBackground(new java.awt.Color(255, 255, 255));
    LocationButton.setFont(new java.awt.Font("VIP Rawy Regular", 0, 24)); // NOI18N
    LocationButton.setText("Location");
    LocationButton.setToolTipText("");
    LocationButton.setBorderPainted(false);
    LocationButton.setContentAreaFilled(false);
    LocationButton.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
    LocationButton.addMouseMotionListener(new java.awt.event.MouseMotionAdapter()
    {
      public void mouseMoved(java.awt.event.MouseEvent evt)
      {
        LocationButtonMouseMoved(evt);
      }
    });
    LocationButton.addMouseListener(new java.awt.event.MouseAdapter()
    {
      public void mousePressed(java.awt.event.MouseEvent evt)
      {
        LocationButtonMousePressed(evt);
      }
      public void mouseExited(java.awt.event.MouseEvent evt)
      {
        LocationButtonMouseExited(evt);
      }
    });
    LocationButton.addActionListener(new java.awt.event.ActionListener()
    {
      public void actionPerformed(java.awt.event.ActionEvent evt)
      {
        LocationButtonActionPerformed(evt);
      }
    });
    locationManagerPanel.add(LocationButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 230, 140, 40));

    FloorButton.setBackground(new java.awt.Color(255, 255, 255));
    FloorButton.setFont(new java.awt.Font("VIP Rawy Regular", 0, 24)); // NOI18N
    FloorButton.setText("Floor");
    FloorButton.setToolTipText("");
    FloorButton.setBorderPainted(false);
    FloorButton.setContentAreaFilled(false);
    FloorButton.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
    FloorButton.addMouseMotionListener(new java.awt.event.MouseMotionAdapter()
    {
      public void mouseMoved(java.awt.event.MouseEvent evt)
      {
        FloorButtonMouseMoved(evt);
      }
    });
    FloorButton.addMouseListener(new java.awt.event.MouseAdapter()
    {
      public void mousePressed(java.awt.event.MouseEvent evt)
      {
        FloorButtonMousePressed(evt);
      }
      public void mouseExited(java.awt.event.MouseEvent evt)
      {
        FloorButtonMouseExited(evt);
      }
    });
    FloorButton.addActionListener(new java.awt.event.ActionListener()
    {
      public void actionPerformed(java.awt.event.ActionEvent evt)
      {
        FloorButtonActionPerformed(evt);
      }
    });
    locationManagerPanel.add(FloorButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 280, 140, 40));

    buildingButton.setBackground(new java.awt.Color(255, 255, 255));
    buildingButton.setFont(new java.awt.Font("VIP Rawy Regular", 0, 24)); // NOI18N
    buildingButton.setText("Building");
    buildingButton.setToolTipText("");
    buildingButton.setBorderPainted(false);
    buildingButton.setContentAreaFilled(false);
    buildingButton.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
    buildingButton.addMouseMotionListener(new java.awt.event.MouseMotionAdapter()
    {
      public void mouseMoved(java.awt.event.MouseEvent evt)
      {
        buildingButtonMouseMoved(evt);
      }
    });
    buildingButton.addMouseListener(new java.awt.event.MouseAdapter()
    {
      public void mousePressed(java.awt.event.MouseEvent evt)
      {
        buildingButtonMousePressed(evt);
      }
      public void mouseExited(java.awt.event.MouseEvent evt)
      {
        buildingButtonMouseExited(evt);
      }
    });
    buildingButton.addActionListener(new java.awt.event.ActionListener()
    {
      public void actionPerformed(java.awt.event.ActionEvent evt)
      {
        buildingButtonActionPerformed(evt);
      }
    });
    locationManagerPanel.add(buildingButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 330, 140, 40));

    LocationTypeButton.setBackground(new java.awt.Color(255, 255, 255));
    LocationTypeButton.setFont(new java.awt.Font("VIP Rawy Regular", 0, 24)); // NOI18N
    LocationTypeButton.setText("Location type");
    LocationTypeButton.setToolTipText("");
    LocationTypeButton.setBorderPainted(false);
    LocationTypeButton.setContentAreaFilled(false);
    LocationTypeButton.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
    LocationTypeButton.addMouseMotionListener(new java.awt.event.MouseMotionAdapter()
    {
      public void mouseMoved(java.awt.event.MouseEvent evt)
      {
        LocationTypeButtonMouseMoved(evt);
      }
    });
    LocationTypeButton.addMouseListener(new java.awt.event.MouseAdapter()
    {
      public void mousePressed(java.awt.event.MouseEvent evt)
      {
        LocationTypeButtonMousePressed(evt);
      }
      public void mouseExited(java.awt.event.MouseEvent evt)
      {
        LocationTypeButtonMouseExited(evt);
      }
    });
    LocationTypeButton.addActionListener(new java.awt.event.ActionListener()
    {
      public void actionPerformed(java.awt.event.ActionEvent evt)
      {
        LocationTypeButtonActionPerformed(evt);
      }
    });
    locationManagerPanel.add(LocationTypeButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 180, 210, 40));

    add(locationManagerPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 60, 390, 400));

    usersManagerPanel.setBackground(new java.awt.Color(255, 255, 255));
    usersManagerPanel.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
    usersManagerPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

    userSectionImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/fym/lta/Images/icons8_user_group_man_woman_128px.png"))); // NOI18N
    usersManagerPanel.add(userSectionImage, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 20, -1, -1));

    arrow16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/fym/lta/Images/icons8_circled_chevron_right_filled_30px.png"))); // NOI18N
    usersManagerPanel.add(arrow16, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 170, -1, 40));

    arrow17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/fym/lta/Images/icons8_circled_chevron_right_filled_30px.png"))); // NOI18N
    usersManagerPanel.add(arrow17, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 220, -1, 41));

    arrow18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/fym/lta/Images/icons8_circled_chevron_right_filled_30px.png"))); // NOI18N
    usersManagerPanel.add(arrow18, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 270, -1, 42));

    arrow19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/fym/lta/Images/icons8_circled_chevron_right_filled_30px.png"))); // NOI18N
    usersManagerPanel.add(arrow19, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 320, -1, 40));

    UserButton.setBackground(new java.awt.Color(255, 255, 255));
    UserButton.setFont(new java.awt.Font("VIP Rawy Regular", 0, 24)); // NOI18N
    UserButton.setText("Users");
    UserButton.setToolTipText("");
    UserButton.setBorderPainted(false);
    UserButton.setContentAreaFilled(false);
    UserButton.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
    UserButton.addMouseMotionListener(new java.awt.event.MouseMotionAdapter()
    {
      public void mouseMoved(java.awt.event.MouseEvent evt)
      {
        UserButtonMouseMoved(evt);
      }
    });
    UserButton.addMouseListener(new java.awt.event.MouseAdapter()
    {
      public void mousePressed(java.awt.event.MouseEvent evt)
      {
        UserButtonMousePressed(evt);
      }
      public void mouseExited(java.awt.event.MouseEvent evt)
      {
        UserButtonMouseExited(evt);
      }
    });
    UserButton.addActionListener(new java.awt.event.ActionListener()
    {
      public void actionPerformed(java.awt.event.ActionEvent evt)
      {
        UserButtonActionPerformed(evt);
      }
    });
    usersManagerPanel.add(UserButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 220, 140, 40));

    RoleButton.setBackground(new java.awt.Color(255, 255, 255));
    RoleButton.setFont(new java.awt.Font("VIP Rawy Regular", 0, 24)); // NOI18N
    RoleButton.setText("User roles");
    RoleButton.setToolTipText("");
    RoleButton.setBorderPainted(false);
    RoleButton.setContentAreaFilled(false);
    RoleButton.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
    RoleButton.addMouseMotionListener(new java.awt.event.MouseMotionAdapter()
    {
      public void mouseMoved(java.awt.event.MouseEvent evt)
      {
        RoleButtonMouseMoved(evt);
      }
    });
    RoleButton.addMouseListener(new java.awt.event.MouseAdapter()
    {
      public void mousePressed(java.awt.event.MouseEvent evt)
      {
        RoleButtonMousePressed(evt);
      }
      public void mouseExited(java.awt.event.MouseEvent evt)
      {
        RoleButtonMouseExited(evt);
      }
    });
    RoleButton.addActionListener(new java.awt.event.ActionListener()
    {
      public void actionPerformed(java.awt.event.ActionEvent evt)
      {
        RoleButtonActionPerformed(evt);
      }
    });
    usersManagerPanel.add(RoleButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 270, 140, 40));

    RoleScreenButton.setBackground(new java.awt.Color(255, 255, 255));
    RoleScreenButton.setFont(new java.awt.Font("VIP Rawy Regular", 0, 24)); // NOI18N
    RoleScreenButton.setText("Role screen");
    RoleScreenButton.setToolTipText("");
    RoleScreenButton.setBorderPainted(false);
    RoleScreenButton.setContentAreaFilled(false);
    RoleScreenButton.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
    RoleScreenButton.addMouseMotionListener(new java.awt.event.MouseMotionAdapter()
    {
      public void mouseMoved(java.awt.event.MouseEvent evt)
      {
        RoleScreenButtonMouseMoved(evt);
      }
    });
    RoleScreenButton.addMouseListener(new java.awt.event.MouseAdapter()
    {
      public void mousePressed(java.awt.event.MouseEvent evt)
      {
        RoleScreenButtonMousePressed(evt);
      }
      public void mouseExited(java.awt.event.MouseEvent evt)
      {
        RoleScreenButtonMouseExited(evt);
      }
    });
    RoleScreenButton.addActionListener(new java.awt.event.ActionListener()
    {
      public void actionPerformed(java.awt.event.ActionEvent evt)
      {
        RoleScreenButtonActionPerformed(evt);
      }
    });
    usersManagerPanel.add(RoleScreenButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 320, 190, 40));

    EmployeeButton.setBackground(new java.awt.Color(255, 255, 255));
    EmployeeButton.setFont(new java.awt.Font("VIP Rawy Regular", 0, 24)); // NOI18N
    EmployeeButton.setText("Employees");
    EmployeeButton.setToolTipText("");
    EmployeeButton.setBorderPainted(false);
    EmployeeButton.setContentAreaFilled(false);
    EmployeeButton.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
    EmployeeButton.addMouseMotionListener(new java.awt.event.MouseMotionAdapter()
    {
      public void mouseMoved(java.awt.event.MouseEvent evt)
      {
        EmployeeButtonMouseMoved(evt);
      }
    });
    EmployeeButton.addMouseListener(new java.awt.event.MouseAdapter()
    {
      public void mousePressed(java.awt.event.MouseEvent evt)
      {
        EmployeeButtonMousePressed(evt);
      }
      public void mouseExited(java.awt.event.MouseEvent evt)
      {
        EmployeeButtonMouseExited(evt);
      }
    });
    EmployeeButton.addActionListener(new java.awt.event.ActionListener()
    {
      public void actionPerformed(java.awt.event.ActionEvent evt)
      {
        EmployeeButtonActionPerformed(evt);
      }
    });
    usersManagerPanel.add(EmployeeButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 170, 210, 40));

    add(usersManagerPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 510, 390, 400));

    getAccessibleContext().setAccessibleName("");
    getAccessibleContext().setAccessibleDescription("");
  }//GEN-END:initComponents

  private void LocationButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_LocationButtonActionPerformed
  {//GEN-HEADEREND:event_LocationButtonActionPerformed
    // TODO add your handling code here:
    try
      {
        //create location panel
        LocationPanel location_panel = new LocationPanel(user);
        //set panel bounds as this panel
        location_panel.setBounds(this.getBounds());
        this.removeAll();  //remove all component in this panel
        this.revalidate(); //revalidate it
        this.repaint();    //repaint it
        this.add(location_panel);  //add loction panel to this panel

      }
    catch(Exception e)
      {
        e.printStackTrace();
      }
  }//GEN-LAST:event_LocationButtonActionPerformed

  private void FloorButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_FloorButtonActionPerformed
  {//GEN-HEADEREND:event_FloorButtonActionPerformed
    // TODO add your handling code here:
    try
      {
        //create floor panel
        FloorPanel floor_panel = new FloorPanel(user);
        //set panel bounds as this panel
        floor_panel.setBounds(this.getBounds());
        this.removeAll(); //remove all component in this panel
        this.revalidate(); //revalidate it
        this.repaint(); //repaint it
        this.add(floor_panel); //add floor panel to this panel
      }
    catch(Exception e)
      {
        e.printStackTrace();
      }
  }//GEN-LAST:event_FloorButtonActionPerformed

  private void buildingButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_buildingButtonActionPerformed
  {//GEN-HEADEREND:event_buildingButtonActionPerformed
    // TODO add your handling code here:

    try
      {
        //create building panel
        BuildingPanel building_panel = new BuildingPanel(user);
        //set panel bounds as this panel
        building_panel.setBounds(this.getBounds());
        this.removeAll(); //remove all component in this panel
        this.revalidate(); //revalidate it
        this.repaint(); //repaint it
        this.add(building_panel); //add building panel to this panel
      }
    catch(Exception e)
      {
        e.printStackTrace();
      }
  }//GEN-LAST:event_buildingButtonActionPerformed

  private void LocationTypeButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_LocationTypeButtonActionPerformed
  {//GEN-HEADEREND:event_LocationTypeButtonActionPerformed
    // TODO add your handling code here:
    try
      {
        //create location type panel
        LocationTypePanel locationType_panel = new LocationTypePanel(user);
        //set panel bounds as this panel
        locationType_panel.setBounds(this.getBounds());
        this.removeAll(); //remove all component in this panel
        this.revalidate(); //revalidate it
        this.repaint(); //repaint it
        this.add(locationType_panel); //add location type panel to this panel
      }
    catch(Exception e)
      {
        e.printStackTrace();
      }
  }//GEN-LAST:event_LocationTypeButtonActionPerformed

  private void CourseButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_CourseButtonActionPerformed
  {//GEN-HEADEREND:event_CourseButtonActionPerformed
    // TODO add your handling code here:
    try
      {
        //create course panel
        CoursePanel course_panel = new CoursePanel(user);
        //set panel bounds as this panel
        course_panel.setBounds(this.getBounds());
        this.removeAll(); //remove all component in this panel
        this.revalidate(); //revalidate it
        this.repaint(); //repaint it
        this.add(course_panel);  //add course panel to this panel
      }
    catch(Exception e)
      {
        e.printStackTrace();
      }
  }//GEN-LAST:event_CourseButtonActionPerformed

  private void StaffButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_StaffButtonActionPerformed
  {//GEN-HEADEREND:event_StaffButtonActionPerformed
    // TODO add your handling code here:
    try
      {
        //create staff panel
        StaffPanel staff_panel = new StaffPanel(user);
        //set panel bounds as this panel
        staff_panel.setBounds(this.getBounds());
        this.removeAll(); //remove all component in this panel
        this.revalidate(); //revalidate it
        this.repaint(); //repaint it
        this.add(staff_panel); //add staff panel to this panel
      }
    catch(Exception e)
      {
        e.printStackTrace();
      }
  }//GEN-LAST:event_StaffButtonActionPerformed

  private void DepartmentButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_DepartmentButtonActionPerformed
  {//GEN-HEADEREND:event_DepartmentButtonActionPerformed
    // TODO add your handling code here:
    try
      {
        //create department panel
        DepartmentPanel department_panel = new DepartmentPanel(user);
        //set panel bounds as this panel
        department_panel.setBounds(this.getBounds());
        this.removeAll(); //remove all component in this panel
        this.revalidate(); //revalidate it
        this.repaint(); //repaint it
        this.add(department_panel); //add department panel to this panel
      }
    catch(Exception e)
      {
        e.printStackTrace();
      }
  }//GEN-LAST:event_DepartmentButtonActionPerformed

  private void DepartmentButtonMousePressed(java.awt.event.MouseEvent evt)//GEN-FIRST:event_DepartmentButtonMousePressed
  {//GEN-HEADEREND:event_DepartmentButtonMousePressed
    
    //change font color to red when user press this button if it enable
    if(DepartmentButton.isEnabled())
      DepartmentButton.setForeground(Color.RED);
  }//GEN-LAST:event_DepartmentButtonMousePressed

  private void DepartmentButtonMouseMoved(java.awt.event.MouseEvent evt)//GEN-FIRST:event_DepartmentButtonMouseMoved
  {//GEN-HEADEREND:event_DepartmentButtonMouseMoved
   
    /* change font color to blue 
     * when user move mouse to this button if it enable */
    if(DepartmentButton.isEnabled())
      DepartmentButton.setForeground(Color.blue);

  }//GEN-LAST:event_DepartmentButtonMouseMoved

  private void DepartmentButtonMouseExited(java.awt.event.MouseEvent evt)//GEN-FIRST:event_DepartmentButtonMouseExited
  {//GEN-HEADEREND:event_DepartmentButtonMouseExited
    
    /* change font color to black
     * when user exit mouse from this button if it enable */
    if(DepartmentButton.isEnabled())
      DepartmentButton.setForeground(Color.black);

  }//GEN-LAST:event_DepartmentButtonMouseExited

  private void CourseButtonMouseExited(java.awt.event.MouseEvent evt)//GEN-FIRST:event_CourseButtonMouseExited
  {//GEN-HEADEREND:event_CourseButtonMouseExited
    
    /* change font color to black
     * when user exit mouse from this button if it enable */
    if(CourseButton.isEnabled())
      CourseButton.setForeground(Color.black);
  }//GEN-LAST:event_CourseButtonMouseExited

  private void CourseButtonMousePressed(java.awt.event.MouseEvent evt)//GEN-FIRST:event_CourseButtonMousePressed
  {//GEN-HEADEREND:event_CourseButtonMousePressed

    //change font color to red when user press this button if it enable
    if(CourseButton.isEnabled())
      CourseButton.setForeground(Color.red);
  }//GEN-LAST:event_CourseButtonMousePressed

  private void CourseButtonMouseMoved(java.awt.event.MouseEvent evt)//GEN-FIRST:event_CourseButtonMouseMoved
  {//GEN-HEADEREND:event_CourseButtonMouseMoved

    /* change font color to blue
     * when user move mouse to this button if it enable */
    if(CourseButton.isEnabled())
      CourseButton.setForeground(Color.blue);

  }//GEN-LAST:event_CourseButtonMouseMoved

  private void StaffButtonMouseExited(java.awt.event.MouseEvent evt)//GEN-FIRST:event_StaffButtonMouseExited
  {//GEN-HEADEREND:event_StaffButtonMouseExited

    /* change font color to black
   * when user exit mouse from this button if it enable */
    if(StaffButton.isEnabled())
      StaffButton.setForeground(Color.black);
  }//GEN-LAST:event_StaffButtonMouseExited

  private void StaffButtonMousePressed(java.awt.event.MouseEvent evt)//GEN-FIRST:event_StaffButtonMousePressed
  {//GEN-HEADEREND:event_StaffButtonMousePressed

    //change font color to red when user press this button if it enable
    if(StaffButton.isEnabled())
      StaffButton.setForeground(Color.red);

  }//GEN-LAST:event_StaffButtonMousePressed

  private void StaffButtonMouseMoved(java.awt.event.MouseEvent evt)//GEN-FIRST:event_StaffButtonMouseMoved
  {//GEN-HEADEREND:event_StaffButtonMouseMoved
   
    /* change font color to blue
     * when user move mouse to this button if it enable */
    if(StaffButton.isEnabled())
      StaffButton.setForeground(Color.blue);

  }//GEN-LAST:event_StaffButtonMouseMoved

  private void LocationTypeButtonMousePressed(java.awt.event.MouseEvent evt)//GEN-FIRST:event_LocationTypeButtonMousePressed
  {//GEN-HEADEREND:event_LocationTypeButtonMousePressed

    //change font color to red when user press this button if it enable
    if(LocationTypeButton.isEnabled())
      LocationTypeButton.setForeground(Color.red);

  }//GEN-LAST:event_LocationTypeButtonMousePressed

  private void LocationTypeButtonMouseExited(java.awt.event.MouseEvent evt)//GEN-FIRST:event_LocationTypeButtonMouseExited
  {//GEN-HEADEREND:event_LocationTypeButtonMouseExited

   /* change font color to black
    * when user exit mouse from this button if it enable */
    if(LocationTypeButton.isEnabled())
      LocationTypeButton.setForeground(Color.black);

  }//GEN-LAST:event_LocationTypeButtonMouseExited

  private void LocationTypeButtonMouseMoved(java.awt.event.MouseEvent evt)//GEN-FIRST:event_LocationTypeButtonMouseMoved
  {//GEN-HEADEREND:event_LocationTypeButtonMouseMoved

    /* change font color to blue
     * when user move mouse to this button if it enable */
    if(LocationTypeButton.isEnabled())
      LocationTypeButton.setForeground(Color.blue);

  }//GEN-LAST:event_LocationTypeButtonMouseMoved

  private void LocationButtonMousePressed(java.awt.event.MouseEvent evt)//GEN-FIRST:event_LocationButtonMousePressed
  {//GEN-HEADEREND:event_LocationButtonMousePressed

    //change font color to red when user press this button if it enable
    if(LocationButton.isEnabled())
      LocationButton.setForeground(Color.red);

  }//GEN-LAST:event_LocationButtonMousePressed

  private void LocationButtonMouseExited(java.awt.event.MouseEvent evt)//GEN-FIRST:event_LocationButtonMouseExited
  {//GEN-HEADEREND:event_LocationButtonMouseExited

    /* change font color to black
     * when user exit mouse from this button if it enable */
    if(LocationButton.isEnabled())
      LocationButton.setForeground(Color.black);

  }//GEN-LAST:event_LocationButtonMouseExited

  private void LocationButtonMouseMoved(java.awt.event.MouseEvent evt)//GEN-FIRST:event_LocationButtonMouseMoved
  {//GEN-HEADEREND:event_LocationButtonMouseMoved

    /* change font color to blue
     * when user move mouse to this button if it enable */
    if(LocationButton.isEnabled())
      LocationButton.setForeground(Color.blue);

  }//GEN-LAST:event_LocationButtonMouseMoved

  private void FloorButtonMousePressed(java.awt.event.MouseEvent evt)//GEN-FIRST:event_FloorButtonMousePressed
  {//GEN-HEADEREND:event_FloorButtonMousePressed

    //change font color to red when user press this button if it enable
    if(FloorButton.isEnabled())
      FloorButton.setForeground(Color.red);

  }//GEN-LAST:event_FloorButtonMousePressed

  private void FloorButtonMouseExited(java.awt.event.MouseEvent evt)//GEN-FIRST:event_FloorButtonMouseExited
  {//GEN-HEADEREND:event_FloorButtonMouseExited

    /* change font color to black
   * when user exit mouse from this button if it enable */
    if(FloorButton.isEnabled())
      FloorButton.setForeground(Color.black);

  }//GEN-LAST:event_FloorButtonMouseExited

  private void FloorButtonMouseMoved(java.awt.event.MouseEvent evt)//GEN-FIRST:event_FloorButtonMouseMoved
  {//GEN-HEADEREND:event_FloorButtonMouseMoved

    /* change font color to blue
     * when user move mouse to this button if it enable */
    if(FloorButton.isEnabled())
      FloorButton.setForeground(Color.blue);

  }//GEN-LAST:event_FloorButtonMouseMoved

  private void buildingButtonMousePressed(java.awt.event.MouseEvent evt)//GEN-FIRST:event_buildingButtonMousePressed
  {//GEN-HEADEREND:event_buildingButtonMousePressed

    //change font color to red when user press this button if it enable
    if(buildingButton.isEnabled())
      buildingButton.setForeground(Color.red);

  }//GEN-LAST:event_buildingButtonMousePressed

  private void buildingButtonMouseExited(java.awt.event.MouseEvent evt)//GEN-FIRST:event_buildingButtonMouseExited
  {//GEN-HEADEREND:event_buildingButtonMouseExited

    /* change font color to black
     * when user exit mouse from this button if it enable */
    if(buildingButton.isEnabled())
      buildingButton.setForeground(Color.black);

  }//GEN-LAST:event_buildingButtonMouseExited

  private void buildingButtonMouseMoved(java.awt.event.MouseEvent evt)//GEN-FIRST:event_buildingButtonMouseMoved
  {//GEN-HEADEREND:event_buildingButtonMouseMoved

    /* change font color to blue
     * when user move mouse to this button if it enable */
    if(buildingButton.isEnabled())
      buildingButton.setForeground(Color.blue);

  }//GEN-LAST:event_buildingButtonMouseMoved

  private void EquipmentTypeButtonMouseMoved(java.awt.event.MouseEvent evt)//GEN-FIRST:event_EquipmentTypeButtonMouseMoved
  {//GEN-HEADEREND:event_EquipmentTypeButtonMouseMoved

    /* change font color to blue
     * when user move mouse to this button if it enable */
    if(EquipmentTypeButton.isEnabled())
      EquipmentTypeButton.setForeground(Color.blue);

  }//GEN-LAST:event_EquipmentTypeButtonMouseMoved

  private void EquipmentTypeButtonMousePressed(java.awt.event.MouseEvent evt)//GEN-FIRST:event_EquipmentTypeButtonMousePressed
  {//GEN-HEADEREND:event_EquipmentTypeButtonMousePressed

    //change font color to red when user press this button if it enable
    if(EquipmentTypeButton.isEnabled())
      EquipmentTypeButton.setForeground(Color.red);

  }//GEN-LAST:event_EquipmentTypeButtonMousePressed

  private void EquipmentTypeButtonMouseExited(java.awt.event.MouseEvent evt)//GEN-FIRST:event_EquipmentTypeButtonMouseExited
  {//GEN-HEADEREND:event_EquipmentTypeButtonMouseExited

    /* change font color to black
     * when user exit mouse from this button if it enable */
    if(EquipmentTypeButton.isEnabled())
      EquipmentTypeButton.setForeground(Color.black);

  }//GEN-LAST:event_EquipmentTypeButtonMouseExited

  private void EquipmentTypeButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_EquipmentTypeButtonActionPerformed
  {//GEN-HEADEREND:event_EquipmentTypeButtonActionPerformed
    try
      {
        //create equipment type panel
        EquipmentTypePanel equip_type_panel = new EquipmentTypePanel(user);
        //set panel bounds as this panel
        equip_type_panel.setBounds(this.getBounds());
        this.removeAll(); //remove all component in this panel
        this.revalidate(); //revalidate it
        this.repaint(); //repaint it      
        this.add(equip_type_panel); //add equipment type panel to this panel
      }
    catch(Exception e)
      {
        e.printStackTrace();
      }
  }//GEN-LAST:event_EquipmentTypeButtonActionPerformed

  private void EquipSpecsButtonMouseMoved(java.awt.event.MouseEvent evt)//GEN-FIRST:event_EquipSpecsButtonMouseMoved
  {//GEN-HEADEREND:event_EquipSpecsButtonMouseMoved
    /* change font color to blue
     * when user move mouse to this button if it enable */
    if(EquipSpecsButton.isEnabled())
      EquipSpecsButton.setForeground(Color.blue);

  }//GEN-LAST:event_EquipSpecsButtonMouseMoved

  private void EquipSpecsButtonMousePressed(java.awt.event.MouseEvent evt)//GEN-FIRST:event_EquipSpecsButtonMousePressed
  {//GEN-HEADEREND:event_EquipSpecsButtonMousePressed
    //change font color to red when user press this button if it enable
    if(EquipSpecsButton.isEnabled())
      EquipSpecsButton.setForeground(Color.red);

  }//GEN-LAST:event_EquipSpecsButtonMousePressed

  private void EquipSpecsButtonMouseExited(java.awt.event.MouseEvent evt)//GEN-FIRST:event_EquipSpecsButtonMouseExited
  {//GEN-HEADEREND:event_EquipSpecsButtonMouseExited
  
    /* change font color to black
     * when user exit mouse from this button if it enable */
    if(EquipSpecsButton.isEnabled())
      EquipSpecsButton.setForeground(Color.black);

  }//GEN-LAST:event_EquipSpecsButtonMouseExited

  private void EquipSpecsButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_EquipSpecsButtonActionPerformed
  {//GEN-HEADEREND:event_EquipSpecsButtonActionPerformed

    try
      {
        //create equipment specs panel
        EqSpecificationPanel equip_specs_panel = new EqSpecificationPanel(user);
        //set panel bounds as this panel
        equip_specs_panel.setBounds(this.getBounds());
        this.removeAll(); //remove all component in this panel
        this.revalidate(); //revalidate it
        this.repaint(); //repaint it
        this.add(equip_specs_panel);  //add equipment specs panel to this panel

      }
    catch(Exception e)
      {
        e.printStackTrace();
      }
  }//GEN-LAST:event_EquipSpecsButtonActionPerformed

  private void EquipmentButtonMouseMoved(java.awt.event.MouseEvent evt)//GEN-FIRST:event_EquipmentButtonMouseMoved
  {//GEN-HEADEREND:event_EquipmentButtonMouseMoved

    /* change font color to blue
     * when user move mouse to this button if it enable */
    if(EquipmentButton.isEnabled())
      EquipmentButton.setForeground(Color.blue);

  }//GEN-LAST:event_EquipmentButtonMouseMoved

  private void EquipmentButtonMousePressed(java.awt.event.MouseEvent evt)//GEN-FIRST:event_EquipmentButtonMousePressed
  {//GEN-HEADEREND:event_EquipmentButtonMousePressed

    //change font color to red when user press this button if it enable
    if(EquipmentButton.isEnabled())
      EquipmentButton.setForeground(Color.red);

  }//GEN-LAST:event_EquipmentButtonMousePressed

  private void EquipmentButtonMouseExited(java.awt.event.MouseEvent evt)//GEN-FIRST:event_EquipmentButtonMouseExited
  {//GEN-HEADEREND:event_EquipmentButtonMouseExited

    /* change font color to black
     * when user exit mouse from this button if it enable */
    if(EquipmentButton.isEnabled())
      EquipmentButton.setForeground(Color.black);

  }//GEN-LAST:event_EquipmentButtonMouseExited

  private void EquipmentButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_EquipmentButtonActionPerformed
  {//GEN-HEADEREND:event_EquipmentButtonActionPerformed

    try
      {
        //create equipment panel
        EquipmentPanel equipment_panel = new EquipmentPanel(user);
        //set panel bounds as this panel
        equipment_panel.setBounds(this.getBounds());
        this.removeAll(); //remove all component in this panel
        this.revalidate(); //revalidate it
        this.repaint(); //repaint it
        this.add(equipment_panel); //add equipment panel to this panel
      }
    catch(Exception e)
      {
        e.printStackTrace();
      }
  }//GEN-LAST:event_EquipmentButtonActionPerformed

  private void UserButtonMouseMoved(java.awt.event.MouseEvent evt)//GEN-FIRST:event_UserButtonMouseMoved
  {//GEN-HEADEREND:event_UserButtonMouseMoved
   
    /* change font color to blue
   * when user move mouse to this button if it enable */
    if(UserButton.isEnabled())
      UserButton.setForeground(Color.blue);
  }//GEN-LAST:event_UserButtonMouseMoved

  private void UserButtonMousePressed(java.awt.event.MouseEvent evt)//GEN-FIRST:event_UserButtonMousePressed
  {//GEN-HEADEREND:event_UserButtonMousePressed

    //change font color to red when user press this button if it enable
    if(UserButton.isEnabled())
      UserButton.setForeground(Color.red);
    
  }//GEN-LAST:event_UserButtonMousePressed

  private void UserButtonMouseExited(java.awt.event.MouseEvent evt)//GEN-FIRST:event_UserButtonMouseExited
  {//GEN-HEADEREND:event_UserButtonMouseExited

    /* change font color to black
     * when user exit mouse from this button if it enable */
    if(UserButton.isEnabled())
      UserButton.setForeground(Color.black);

  }//GEN-LAST:event_UserButtonMouseExited

  private void UserButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_UserButtonActionPerformed
  {//GEN-HEADEREND:event_UserButtonActionPerformed

    try
      {
        //create user panel
        UserPanel user_panel = new UserPanel(user);
        //set panel bounds as this panel
        user_panel.setBounds(this.getBounds());
        this.removeAll(); //remove all component in this panel
        this.revalidate(); //revalidate it
        this.repaint(); //repaint it
        this.add(user_panel);  //add user panel to this panel

      }
    catch(Exception e)
      {
        e.printStackTrace();
      }
  }//GEN-LAST:event_UserButtonActionPerformed

  private void RoleButtonMouseMoved(java.awt.event.MouseEvent evt)//GEN-FIRST:event_RoleButtonMouseMoved
  {//GEN-HEADEREND:event_RoleButtonMouseMoved

    /* change font color to blue
     * when user move mouse to this button if it enable */
    if(RoleButton.isEnabled())
      RoleButton.setForeground(Color.blue);
  }//GEN-LAST:event_RoleButtonMouseMoved

  private void RoleButtonMousePressed(java.awt.event.MouseEvent evt)//GEN-FIRST:event_RoleButtonMousePressed
  {//GEN-HEADEREND:event_RoleButtonMousePressed

    //change font color to red when user press this button if it enable
    if(RoleButton.isEnabled())
      RoleButton.setForeground(Color.red);

  }//GEN-LAST:event_RoleButtonMousePressed

  private void RoleButtonMouseExited(java.awt.event.MouseEvent evt)//GEN-FIRST:event_RoleButtonMouseExited
  {//GEN-HEADEREND:event_RoleButtonMouseExited
    
    /* change font color to black
     * when user exit mouse from this button if it enable */
    if(RoleButton.isEnabled())
      RoleButton.setForeground(Color.black);

  }//GEN-LAST:event_RoleButtonMouseExited

  private void RoleButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_RoleButtonActionPerformed
  {//GEN-HEADEREND:event_RoleButtonActionPerformed
    // TODO add your handling code here:
    try
      {
        //create role panel
        RolePanel user_role_panel = new RolePanel(user);
        //set panel bounds as this panel
        user_role_panel.setBounds(this.getBounds());
        this.removeAll(); //remove all component in this panel
        this.revalidate(); //revalidate it
        this.repaint(); //repaint it
        this.add(user_role_panel); //add role panel to this panel
      }
    catch(Exception e)
      {
        e.printStackTrace();
      }
  }//GEN-LAST:event_RoleButtonActionPerformed

  private void RoleScreenButtonMouseMoved(java.awt.event.MouseEvent evt)//GEN-FIRST:event_RoleScreenButtonMouseMoved
  {//GEN-HEADEREND:event_RoleScreenButtonMouseMoved

    /* change font color to blue
     * when user move mouse to this button if it enable */
    if(RoleScreenButton.isEnabled())
      RoleScreenButton.setForeground(Color.blue);

  }//GEN-LAST:event_RoleScreenButtonMouseMoved

  private void RoleScreenButtonMousePressed(java.awt.event.MouseEvent evt)//GEN-FIRST:event_RoleScreenButtonMousePressed
  {//GEN-HEADEREND:event_RoleScreenButtonMousePressed

    //change font color to red when user press this button if it enable
    if(RoleScreenButton.isEnabled())
      RoleScreenButton.setForeground(Color.red);
  }//GEN-LAST:event_RoleScreenButtonMousePressed

  private void RoleScreenButtonMouseExited(java.awt.event.MouseEvent evt)//GEN-FIRST:event_RoleScreenButtonMouseExited
  {//GEN-HEADEREND:event_RoleScreenButtonMouseExited
    
    /* change font color to black
     * when user exit mouse from this button if it enable */
    if(RoleScreenButton.isEnabled())
      RoleScreenButton.setForeground(Color.black);

  }//GEN-LAST:event_RoleScreenButtonMouseExited

  private void RoleScreenButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_RoleScreenButtonActionPerformed
  {//GEN-HEADEREND:event_RoleScreenButtonActionPerformed

    try
      {
        //create role screen panel
        RoleScreenPanel role_screen_panel = new RoleScreenPanel(user);
        //set panel bounds as this panel
        role_screen_panel.setBounds(this.getBounds());
        this.removeAll(); //remove all component in this panel
        this.revalidate(); //revalidate it
        this.repaint(); //repaint it
        this.add(role_screen_panel); //add role screen panel to this panel
      }
    catch(Exception e)
      {
        e.printStackTrace();
      }
  }//GEN-LAST:event_RoleScreenButtonActionPerformed

  private void EmployeeButtonMouseMoved(java.awt.event.MouseEvent evt)//GEN-FIRST:event_EmployeeButtonMouseMoved
  {//GEN-HEADEREND:event_EmployeeButtonMouseMoved

    /* change font color to blue
     * when user move mouse to this button if it enable */
    if(EmployeeButton.isEnabled())
      EmployeeButton.setForeground(Color.blue);

  }//GEN-LAST:event_EmployeeButtonMouseMoved

  private void EmployeeButtonMousePressed(java.awt.event.MouseEvent evt)//GEN-FIRST:event_EmployeeButtonMousePressed
  {//GEN-HEADEREND:event_EmployeeButtonMousePressed

    //change font color to red when user press this button if it enable
    if(EmployeeButton.isEnabled())
      EmployeeButton.setForeground(Color.red);

  }//GEN-LAST:event_EmployeeButtonMousePressed

  private void EmployeeButtonMouseExited(java.awt.event.MouseEvent evt)//GEN-FIRST:event_EmployeeButtonMouseExited
  {//GEN-HEADEREND:event_EmployeeButtonMouseExited

    /* change font color to black
     * when user exit mouse from this button if it enable */
    if(EmployeeButton.isEnabled())
      EmployeeButton.setForeground(Color.black);

  }//GEN-LAST:event_EmployeeButtonMouseExited

  private void EmployeeButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_EmployeeButtonActionPerformed
  {//GEN-HEADEREND:event_EmployeeButtonActionPerformed

    try
      {
        //create employee panel
        EmployeePanel employee = new EmployeePanel(user);
        //set panel bounds as this panel
        employee.setBounds(this.getBounds());
        this.removeAll(); //remove all component in this panel
        this.revalidate(); //revalidate it
        this.repaint(); //repaint it
        this.add(employee); //add employee panel to this panel
      }
    catch(Exception e) 
      {
        e.printStackTrace();
      }
  }//GEN-LAST:event_EmployeeButtonActionPerformed


  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JButton CourseButton;
  private javax.swing.JButton DepartmentButton;
  private javax.swing.JButton EmployeeButton;
  private javax.swing.JButton EquipSpecsButton;
  private javax.swing.JButton EquipmentButton;
  private javax.swing.JButton EquipmentTypeButton;
  private javax.swing.JButton FloorButton;
  private javax.swing.JLabel LactionSectionImage;
  private javax.swing.JButton LocationButton;
  private javax.swing.JButton LocationTypeButton;
  private javax.swing.JButton RoleButton;
  private javax.swing.JButton RoleScreenButton;
  private javax.swing.JButton StaffButton;
  private javax.swing.JButton UserButton;
  private javax.swing.JLabel arrow1;
  private javax.swing.JLabel arrow11;
  private javax.swing.JLabel arrow12;
  private javax.swing.JLabel arrow13;
  private javax.swing.JLabel arrow16;
  private javax.swing.JLabel arrow17;
  private javax.swing.JLabel arrow18;
  private javax.swing.JLabel arrow19;
  private javax.swing.JLabel arrow3;
  private javax.swing.JLabel arrow4;
  private javax.swing.JLabel arrow5;
  private javax.swing.JLabel arrow7;
  private javax.swing.JLabel arrow8;
  private javax.swing.JLabel arrow9;
  private javax.swing.JButton buildingButton;
  private javax.swing.JPanel departmentManagerPanel;
  private javax.swing.JLabel departmentSectionImage;
  private javax.swing.JPanel equipmentManagerPanel;
  private javax.swing.JLabel equipmentSectionImage;
  private javax.swing.JPanel locationManagerPanel;
  private javax.swing.JLabel userSectionImage;
  private javax.swing.JPanel usersManagerPanel;
  // End of variables declaration//GEN-END:variables

}
