
package com.fym.lta.UI;

import com.fym.lta.BAO.BaoFactory;
import com.fym.lta.BAO.RoleScreenBao;
import com.fym.lta.DTO.UserDto;

import java.awt.Color;

import java.util.ArrayList;

/**
 *
 * @author Mai-AbdEltwab
 */
public class ScheduleMenuPanel extends javax.swing.JPanel
{
  @SuppressWarnings("compatibility:6963988319291739500")
  private static final long serialVersionUID = 1L;

  /**Definitions*/
  //define user dto as "user"
  static UserDto user = null;


  /** Creates new form ScheduleMenuPanel */
  public ScheduleMenuPanel(UserDto user)
  {
    //assign logged in user to user_account object
    ScheduleMenuPanel.user = user;

    //set panel component
    initComponents();

    //set all panels buttons false
    setPanelsFalse();

    //set panels buttons ture which only user has access on it
    checkSecuirty();
  }


  /**This method for role screen
   * set panels buttons ture which only user role has access on it
   * */
  private void checkSecuirty()
  {

    //create role screen bao
    RoleScreenBao userPanel_bao =
      new BaoFactory().createRoleScreenBao(user);

    //get all existing screens for this user
    ArrayList<String> panels =
      new ArrayList<String>(userPanel_bao.checkPanel(user));

    /* get check for each screen
     * if its name match any button text enable this button*/
    for(int i = 0; i<panels.size(); i++)
      {
        //for location occupancy screen
        if(LocationOccupancyButton.getText().equalsIgnoreCase(panels.get(i)))
          LocationOccupancyButton.setEnabled(true);
      
        //for manual assignment screen
        if(ManualAssignButton.getText().equalsIgnoreCase(panels.get(i)))
          ManualAssignButton.setEnabled(true);

        //for schedule screen
        if(scheduleButton.getText().equalsIgnoreCase(panels.get(i)))
          scheduleButton.setEnabled(true);

      }

  }


  /**set method used to set all panels bottuns disable
   * */
  private void setPanelsFalse()
  {

    LocationOccupancyButton.setEnabled(false);
    ManualAssignButton.setEnabled(false);
    scheduleButton.setEnabled(false);

  }

  /** This method is called from within the constructor to
   * initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is
   * always regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  private void initComponents()//GEN-BEGIN:initComponents
  {

    schedulePanel = new javax.swing.JPanel();
    sheduleSectionImage = new javax.swing.JLabel();
    arrow1 = new javax.swing.JLabel();
    scheduleButton = new javax.swing.JButton();
    ManualAssignButton = new javax.swing.JButton();
    arrow2 = new javax.swing.JLabel();
    locationManagerPanel = new javax.swing.JPanel();
    locationSectionImage = new javax.swing.JLabel();
    LocationOccupancyButton = new javax.swing.JButton();
    arrow3 = new javax.swing.JLabel();
    usersManagerPanel = new javax.swing.JPanel();
    userSectionImage = new javax.swing.JLabel();
    arrow16 = new javax.swing.JLabel();
    EmployeeButton = new javax.swing.JButton();

    setBackground(new java.awt.Color(228, 228, 228));
    setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

    schedulePanel.setBackground(new java.awt.Color(255, 255, 255));
    schedulePanel.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
    schedulePanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

    sheduleSectionImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/fym/lta/Images/icons8_calendar_128px.png"))); // NOI18N
    schedulePanel.add(sheduleSectionImage, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 30, -1, -1));

    arrow1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/fym/lta/Images/icons8_circled_chevron_right_filled_30px.png"))); // NOI18N
    schedulePanel.add(arrow1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 200, 50, 40));

    scheduleButton.setBackground(new java.awt.Color(255, 255, 255));
    scheduleButton.setFont(new java.awt.Font("VIP Rawy Regular", 0, 30)); // NOI18N
    scheduleButton.setText("Schedule");
    scheduleButton.setToolTipText("");
    scheduleButton.setBorderPainted(false);
    scheduleButton.setContentAreaFilled(false);
    scheduleButton.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
    scheduleButton.addMouseMotionListener(new java.awt.event.MouseMotionAdapter()
    {
      public void mouseMoved(java.awt.event.MouseEvent evt)
      {
        scheduleButtonMouseMoved(evt);
      }
    });
    scheduleButton.addMouseListener(new java.awt.event.MouseAdapter()
    {
      public void mousePressed(java.awt.event.MouseEvent evt)
      {
        scheduleButtonMousePressed(evt);
      }
      public void mouseExited(java.awt.event.MouseEvent evt)
      {
        scheduleButtonMouseExited(evt);
      }
    });
    scheduleButton.addActionListener(new java.awt.event.ActionListener()
    {
      public void actionPerformed(java.awt.event.ActionEvent evt)
      {
        scheduleButtonActionPerformed(evt);
      }
    });
    schedulePanel.add(scheduleButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 200, 150, 40));

    ManualAssignButton.setBackground(new java.awt.Color(255, 255, 255));
    ManualAssignButton.setFont(new java.awt.Font("VIP Rawy Regular", 0, 30)); // NOI18N
    ManualAssignButton.setText("Manual assignment");
    ManualAssignButton.setToolTipText("");
    ManualAssignButton.setBorderPainted(false);
    ManualAssignButton.setContentAreaFilled(false);
    ManualAssignButton.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
    ManualAssignButton.addMouseMotionListener(new java.awt.event.MouseMotionAdapter()
    {
      public void mouseMoved(java.awt.event.MouseEvent evt)
      {
        ManualAssignButtonMouseMoved(evt);
      }
    });
    ManualAssignButton.addMouseListener(new java.awt.event.MouseAdapter()
    {
      public void mousePressed(java.awt.event.MouseEvent evt)
      {
        ManualAssignButtonMousePressed(evt);
      }
      public void mouseExited(java.awt.event.MouseEvent evt)
      {
        ManualAssignButtonMouseExited(evt);
      }
    });
    ManualAssignButton.addActionListener(new java.awt.event.ActionListener()
    {
      public void actionPerformed(java.awt.event.ActionEvent evt)
      {
        ManualAssignButtonActionPerformed(evt);
      }
    });
    schedulePanel.add(ManualAssignButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 240, 340, 40));

    arrow2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/fym/lta/Images/icons8_circled_chevron_right_filled_30px.png"))); // NOI18N
    schedulePanel.add(arrow2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 240, -1, 41));

    add(schedulePanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 40, 510, 350));

    locationManagerPanel.setBackground(new java.awt.Color(255, 255, 255));
    locationManagerPanel.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
    locationManagerPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

    locationSectionImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/fym/lta/Images/icons8_geo_fence_128px.png"))); // NOI18N
    locationManagerPanel.add(locationSectionImage, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 50, -1, -1));

    LocationOccupancyButton.setBackground(new java.awt.Color(255, 255, 255));
    LocationOccupancyButton.setFont(new java.awt.Font("VIP Rawy Regular", 0, 30)); // NOI18N
    LocationOccupancyButton.setText("Location occupancy");
    LocationOccupancyButton.setToolTipText("");
    LocationOccupancyButton.setBorderPainted(false);
    LocationOccupancyButton.setContentAreaFilled(false);
    LocationOccupancyButton.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
    LocationOccupancyButton.addMouseMotionListener(new java.awt.event.MouseMotionAdapter()
    {
      public void mouseMoved(java.awt.event.MouseEvent evt)
      {
        LocationOccupancyButtonMouseMoved(evt);
      }
    });
    LocationOccupancyButton.addMouseListener(new java.awt.event.MouseAdapter()
    {
      public void mousePressed(java.awt.event.MouseEvent evt)
      {
        LocationOccupancyButtonMousePressed(evt);
      }
      public void mouseExited(java.awt.event.MouseEvent evt)
      {
        LocationOccupancyButtonMouseExited(evt);
      }
    });
    LocationOccupancyButton.addActionListener(new java.awt.event.ActionListener()
    {
      public void actionPerformed(java.awt.event.ActionEvent evt)
      {
        LocationOccupancyButtonActionPerformed(evt);
      }
    });
    locationManagerPanel.add(LocationOccupancyButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 230, 340, 40));

    arrow3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/fym/lta/Images/icons8_circled_chevron_right_filled_30px.png"))); // NOI18N
    locationManagerPanel.add(arrow3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 230, 30, 40));

    add(locationManagerPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 490, 510, 340));

    usersManagerPanel.setBackground(new java.awt.Color(255, 255, 255));
    usersManagerPanel.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
    usersManagerPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

    userSectionImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/fym/lta/Images/icons8_user_group_man_woman_128px.png"))); // NOI18N
    usersManagerPanel.add(userSectionImage, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 50, -1, -1));

    arrow16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/fym/lta/Images/icons8_circled_chevron_right_filled_30px.png"))); // NOI18N
    usersManagerPanel.add(arrow16, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 230, 60, 40));

    EmployeeButton.setBackground(new java.awt.Color(255, 255, 255));
    EmployeeButton.setFont(new java.awt.Font("VIP Rawy Regular", 0, 30)); // NOI18N
    EmployeeButton.setText("Staff load");
    EmployeeButton.setToolTipText("");
    EmployeeButton.setBorderPainted(false);
    EmployeeButton.setContentAreaFilled(false);
    EmployeeButton.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
    EmployeeButton.addMouseMotionListener(new java.awt.event.MouseMotionAdapter()
    {
      public void mouseMoved(java.awt.event.MouseEvent evt)
      {
        EmployeeButtonMouseMoved(evt);
      }
    });
    EmployeeButton.addMouseListener(new java.awt.event.MouseAdapter()
    {
      public void mousePressed(java.awt.event.MouseEvent evt)
      {
        EmployeeButtonMousePressed(evt);
      }
      public void mouseExited(java.awt.event.MouseEvent evt)
      {
        EmployeeButtonMouseExited(evt);
      }
    });
    EmployeeButton.addActionListener(new java.awt.event.ActionListener()
    {
      public void actionPerformed(java.awt.event.ActionEvent evt)
      {
        EmployeeButtonActionPerformed(evt);
      }
    });
    usersManagerPanel.add(EmployeeButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 230, 240, 40));

    add(usersManagerPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 490, 510, 340));
  }//GEN-END:initComponents

  private void scheduleButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_scheduleButtonActionPerformed
  {//GEN-HEADEREND:event_scheduleButtonActionPerformed

    try
      {
        //create schedule panel
        SchedulePanel schedule_panel = new SchedulePanel(user);
        //set panel bounds as this panel
        schedule_panel.setBounds(this.getBounds());
        this.removeAll(); //remove all component in this panel
        this.revalidate(); //revalidate it
        this.repaint(); //repaint it
        this.add(schedule_panel); //add schedule panel to this panel
      }
    catch(Exception e)
      {
        e.printStackTrace();
      }
  }//GEN-LAST:event_scheduleButtonActionPerformed

  private void scheduleButtonMouseExited(java.awt.event.MouseEvent evt)//GEN-FIRST:event_scheduleButtonMouseExited
  {//GEN-HEADEREND:event_scheduleButtonMouseExited

    /* change font color to black
     * when user exit mouse from this button if it enable */
    if(scheduleButton.isEnabled())
      scheduleButton.setForeground(Color.black);
  }//GEN-LAST:event_scheduleButtonMouseExited

  private void scheduleButtonMousePressed(java.awt.event.MouseEvent evt)//GEN-FIRST:event_scheduleButtonMousePressed
  {//GEN-HEADEREND:event_scheduleButtonMousePressed

    //change font color to red when user press this button if it enable
    if(scheduleButton.isEnabled())
      scheduleButton.setForeground(Color.red);
  }//GEN-LAST:event_scheduleButtonMousePressed

  private void scheduleButtonMouseMoved(java.awt.event.MouseEvent evt)//GEN-FIRST:event_scheduleButtonMouseMoved
  {//GEN-HEADEREND:event_scheduleButtonMouseMoved

    /* change font color to blue
     * when user move mouse to this button if it enable */
    if(scheduleButton.isEnabled())
      scheduleButton.setForeground(Color.blue);
  }//GEN-LAST:event_scheduleButtonMouseMoved

  private void LocationOccupancyButtonMouseMoved(java.awt.event.MouseEvent evt)//GEN-FIRST:event_LocationOccupancyButtonMouseMoved
  {//GEN-HEADEREND:event_LocationOccupancyButtonMouseMoved

    /* change font color to blue
     * when user move mouse to this button if it enable */
    if(LocationOccupancyButton.isEnabled())
      LocationOccupancyButton.setForeground(Color.blue);
  }//GEN-LAST:event_LocationOccupancyButtonMouseMoved

  private void LocationOccupancyButtonMousePressed(java.awt.event.MouseEvent evt)//GEN-FIRST:event_LocationOccupancyButtonMousePressed
  {//GEN-HEADEREND:event_LocationOccupancyButtonMousePressed

    //change font color to red when user press this button if it enable
    if(LocationOccupancyButton.isEnabled())
      LocationOccupancyButton.setForeground(Color.red);
  }//GEN-LAST:event_LocationOccupancyButtonMousePressed

  private void LocationOccupancyButtonMouseExited(java.awt.event.MouseEvent evt)//GEN-FIRST:event_LocationOccupancyButtonMouseExited
  {//GEN-HEADEREND:event_LocationOccupancyButtonMouseExited
   
    /* change font color to black
     * when user exit mouse from this button if it enable */
    if(LocationOccupancyButton.isEnabled())
      LocationOccupancyButton.setForeground(Color.black);
  }//GEN-LAST:event_LocationOccupancyButtonMouseExited

  private void LocationOccupancyButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_LocationOccupancyButtonActionPerformed
  {//GEN-HEADEREND:event_LocationOccupancyButtonActionPerformed

    try
      {
        //create location occupancy panel
        LocationOccupancyPanel locationOccupancyPanel =
          new LocationOccupancyPanel(user);
        //set panel bounds as this panel
        locationOccupancyPanel.setBounds(this.getBounds());
        this.removeAll(); //remove all component in this panel
        this.revalidate(); //revalidate it
        this.repaint(); //repaint it
        this.add(locationOccupancyPanel); //add location occupancy panel to this panel

      }
    catch(Exception e)
      {
        e.printStackTrace();
      }
  }//GEN-LAST:event_LocationOccupancyButtonActionPerformed

  private void ManualAssignButtonMouseMoved(java.awt.event.MouseEvent evt)//GEN-FIRST:event_ManualAssignButtonMouseMoved
  {//GEN-HEADEREND:event_ManualAssignButtonMouseMoved

    /* change font color to blue
     * when user move mouse to this button if it enable */
    if(ManualAssignButton.isEnabled())
      ManualAssignButton.setForeground(Color.blue);
  }//GEN-LAST:event_ManualAssignButtonMouseMoved

  private void ManualAssignButtonMousePressed(java.awt.event.MouseEvent evt)//GEN-FIRST:event_ManualAssignButtonMousePressed
  {//GEN-HEADEREND:event_ManualAssignButtonMousePressed

    //change font color to red when user press this button if it enable
    if(ManualAssignButton.isEnabled())
      ManualAssignButton.setForeground(Color.red);
  }//GEN-LAST:event_ManualAssignButtonMousePressed

  private void ManualAssignButtonMouseExited(java.awt.event.MouseEvent evt)//GEN-FIRST:event_ManualAssignButtonMouseExited
  {//GEN-HEADEREND:event_ManualAssignButtonMouseExited

    /* change font color to black
     * when user exit mouse from this button if it enable */
    if(ManualAssignButton.isEnabled())
      ManualAssignButton.setForeground(Color.black);
  }//GEN-LAST:event_ManualAssignButtonMouseExited

  private void ManualAssignButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_ManualAssignButtonActionPerformed
  {//GEN-HEADEREND:event_ManualAssignButtonActionPerformed
    // TODO add your handling code here:
    try
      {
        //create manual assignment panel
        ManualAssPanel manualAssPanel = new ManualAssPanel(user);
        //set panel bounds as this panel
        manualAssPanel.setBounds(this.getBounds());
        this.removeAll(); //remove all component in this panel
        this.revalidate(); //revalidate it
        this.repaint(); //repaint it
        this.add(manualAssPanel); //add  manual assignment panel to this panel

      }
    catch(Exception e)
      {
        e.printStackTrace();
      }
  }//GEN-LAST:event_ManualAssignButtonActionPerformed

  private void EmployeeButtonMouseMoved(java.awt.event.MouseEvent evt)//GEN-FIRST:event_EmployeeButtonMouseMoved
  {//GEN-HEADEREND:event_EmployeeButtonMouseMoved

    /* change font color to blue
    * when user move mouse to this button if it enable */
    if(EmployeeButton.isEnabled())
    EmployeeButton.setForeground(Color.blue);
  }//GEN-LAST:event_EmployeeButtonMouseMoved

  private void EmployeeButtonMousePressed(java.awt.event.MouseEvent evt)//GEN-FIRST:event_EmployeeButtonMousePressed
  {//GEN-HEADEREND:event_EmployeeButtonMousePressed

    //change font color to red when user press this button if it enable
    if(EmployeeButton.isEnabled())
    EmployeeButton.setForeground(Color.red);
  }//GEN-LAST:event_EmployeeButtonMousePressed

  private void EmployeeButtonMouseExited(java.awt.event.MouseEvent evt)//GEN-FIRST:event_EmployeeButtonMouseExited
  {//GEN-HEADEREND:event_EmployeeButtonMouseExited

    /* change font color to black
    * when user exit mouse from this button if it enable */
    if(EmployeeButton.isEnabled())
    EmployeeButton.setForeground(Color.black);
  }//GEN-LAST:event_EmployeeButtonMouseExited

  private void EmployeeButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_EmployeeButtonActionPerformed
  {//GEN-HEADEREND:event_EmployeeButtonActionPerformed

    try
    {
      //create staff load panel
      StaffLoadPanel employee = new StaffLoadPanel(user);
      //set panel bounds as this panel
      employee.setBounds(this.getBounds());
      this.removeAll(); //remove all component in this panel
      this.revalidate(); //revalidate it
      this.repaint(); //repaint it
      this.add(employee); //add employee panel to this panel
    }
    catch(Exception e)
    {
      e.printStackTrace();
    }
  }//GEN-LAST:event_EmployeeButtonActionPerformed


  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JButton EmployeeButton;
  private javax.swing.JButton LocationOccupancyButton;
  private javax.swing.JButton ManualAssignButton;
  private javax.swing.JLabel arrow1;
  private javax.swing.JLabel arrow16;
  private javax.swing.JLabel arrow2;
  private javax.swing.JLabel arrow3;
  private javax.swing.JPanel locationManagerPanel;
  private javax.swing.JLabel locationSectionImage;
  private javax.swing.JButton scheduleButton;
  private javax.swing.JPanel schedulePanel;
  private javax.swing.JLabel sheduleSectionImage;
  private javax.swing.JLabel userSectionImage;
  private javax.swing.JPanel usersManagerPanel;
  // End of variables declaration//GEN-END:variables

}
